spring.application.name=backend-new

# postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/skillscape_db
spring.datasource.username=skillscape_user
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# jwt
skillscape.app.jwtSecret=ulHkhRnwa5ngE7^79eBhVYJ%WAKM*$FQBf2@nnyA$n7NZRP#clKAYMGThbqFf2Sr
skillscape.app.jwtExpirationMs=86400000